marcosdosea/GestaoGrupoMusical

- Codigo/Core/Service/IPessoaService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
- Codigo/GestaoGrupoMusicalWeb/Mapper/PessoaProfile.cs
- Codigo/GestaoGrupoMusicalWeb/Models/PessoaViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Program.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Create.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Delete.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Details.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Edit.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Index.cshtml
- Codigo/Service/PessoaService.cs
Inserção no banco para teste:
```
INSERT INTO grupomusical VALUES(1, "Batalá - SE", "Batala Group", "22884507000198", "69309215",
"Travessa dos Imigrantes","Buritis", "Boa Vista", "RR" , "Brasil",
"batalateste@gmail.com", "/batalaRR", "@batalaRR", "/batalaRR", "(27) 2463-7172",
"(82) 2399-2069", "do Brasiiiil", "9999", "1739306-5", "394.464.570-76",  "CPF")
INSERT INTO papelgrupo VALUES (1, "associado"),
(2, "colaborador")
INSERT INTO MANEQUIM VALUES (1,"PP","Extra Pequeno"),
(2,"P","Pequeno"),
(3,"M","MEDIO"),
(4,"G","Grande")
```
> Implementado UC - Manter Associados

- Codigo/Core/Apresentacaotipoinstrumento.cs
- Codigo/Core/Core.csproj
- Codigo/Core/Evento.cs
- Codigo/Core/Eventopessoa.cs
- Codigo/Core/Figurino.cs
- Codigo/Core/GrupoMusicalContext.cs
- Codigo/Core/Grupomusical.cs
- Codigo/Core/Instrumentomusical.cs
- Codigo/Core/Manequim.cs
- Codigo/Core/Materialestudo.cs
- Codigo/Core/Movimentacaofigurino.cs
- Codigo/Core/Pessoa.cs
- Codigo/Core/Receitafinanceira.cs
- Codigo/Core/Receitafinanceirapessoa.cs
- Codigo/Core/Tipoinstrumento.cs
- Scaffolding do modelo de banco de dados da data (25/05/2023)
> Feito Scaffolding (#19)

- Codigo/GestaoGrupoMusicalWeb/Models/GrupoMusicalViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Create.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Edit.cshtml
…ay e stringlength nos atributos, e tambem removendo os ID das Views/GrupoMusical/Create.cshtml e Views/GrupoMusical/Edit.cshtml
> Alteração na Classe Model e remoção dos ID da View Create e Edit

- Codigo/GestaoGrupoMusicalWeb/Models/EventoViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Models/GrupoMusicalViewModel.cs
- Codigo/GestaoGrupoMusicalWebTests/Controllers/EventoControllerTests.cs
- Codigo/ServiceTests/EventoServiceTests.cs
Teste em EventoControllerTests e EventoServiceTests. resolve #39
> Implementacão do testes de UC-Evento

- Codigo/GestaoGrupoMusicalWebTests/Controllers/InstrumentoMusicalControllerTests.cs
- Codigo/ServiceTests/InstrumentoMusicalServiceTests.cs
- 1º: revisar o código do arquivo "InstrumentoMusicalServiceTests.cs";
- 2º revisar o código do arquivo  "InstrumentoMusicalControllerTests.cs".
> Teste de Unidade do UC - Manter Instrumento Musical

- Codigo/ServiceTests/GrupoMusicalServiceTests.cs
- Implementação do método (Codigo\ServiceTests\GrupoMusicalServiceTests.cs).
> UC - Manter Grupo Musical : Teste do método GetAllDTO

- Codigo/Core/Service/IManequim.cs
- Codigo/Service/ManequimService.cs
* criada interface service para entidade manequim
* criado service para entidade manequim
> criada interface service e service para Manequim

- Codigo/ServiceTests/EventoServiceTests.cs
feature: implementação da GetAllDTO.
> Implementado GETALLDTO teste na Service/Evento

- Codigo/Core/DTO/InstrumentoMusicalDTO.cs
- Codigo/Core/DTO/MovimentacaoInstrumentoDTO.cs
- Codigo/Core/Service/IInstrumentoMusicalService.cs
- Codigo/Core/Service/IMovimentacaoInstrumentoService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
- Codigo/GestaoGrupoMusicalWeb/Models/MovimentacaoInstrumentoViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Program.cs
- Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Index.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Movimentar.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/_TabelaMovimentacao.cshtml
- Codigo/Service/InstrumentoMusicalService.cs
- Codigo/Service/MovimentacaoInstrumentoService.cs
- Empréstimo de Instrumento
- Devolução de Instrumento
- DTOs para exibição das correspondentes tabelas
- Cadastro de MovimentacaoInstrumento
- Exclusão de MovimentacaoInstrumento
- Consulta de instrumento em empréstimo
- Select List para inputs do tipo Id
- Tradução da view Index de Instrumento Musical
- Validação para campos vazios
- Não existe o campo "Colaborador" no protótipo original (ESSE CAMPO SERÁ REMOVIDO APÓS AUTENTICAÇÃO E AUTORIZAÇÃO)
```
INSERT INTO grupomusical VALUES(1, "Batalá - SE", "Batala Group", "22884507000198", "69309215",
"Travessa dos Imigrantes","Buritis", "Boa Vista", "RR" , "Brasil",
"batalateste@gmail.com", "/batalaRR", "@batalaRR", "/batalaRR", "(27) 2463-7172",
"(82) 2399-2069", "do Brasiiiil", "9999", "1739306-5", "394.464.570-76",  "CPF");
INSERT INTO …
```
> Entrega e Devolução de Instrumento

- Codigo/Email/Email.csproj
- Codigo/Email/EmailModel.cs
- Codigo/Email/EmailService.cs
- Codigo/GestaoGrupoMusical.sln
- Projeto Email
- Classe static EmailService
- Método EnviarEmail
- Model EmailModel
> Add modulo de e-mail

- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/ChangeToCollaborator.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Create.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Delete.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Details.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Edit.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Index.cshtml
- Verificar se os textos de todas as views do "UC Manter Associados" estão traduzidas.
> Tradução dos textos da view: UC - Manter Associados 

- Codigo/GestaoGrupoMusicalWeb/Models/PessoaViewModel.cs
fix: Alterando PessoaViewModel.cs, colocando os campos required de acordo com o banco
> fix: Alterando PessoaViewModel.cs, colocando os campos required de acordo com o banco

- Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
- Codigo/GestaoGrupoMusicalWeb/Models/EventoViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Evento/Create.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Evento/Delete.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Evento/Details.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Evento/Edit.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Evento/Index.cshtml
- Codigo/GestaoGrupoMusicalWebTests/Controllers/EventoControllerTests.cs
fix:*traduções da tela de criar evento dos botões e labels
fix:*traduções da tela de editar evento dos botões e labels
fix:*traduções da tela de excluir evento dos botões e labels
fix:*traduções da tela de detalhes evento dos botões e labels
fix:*Adicionados select em criar evento e editar evento
#55
> Traduções das Views de UC-Manter Evento

- Codigo/GestaoGrupoMusicalWeb/Models/PessoaViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/ChangeToCollaborator.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Create.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Delete.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Details.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Edit.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Index.cshtml
* adicionado campo de IsentoPagamento nas views e na model
> Adicionado campo de isento pagamento nas views de Pessoa/Associado.

- Codigo/Core/DTO/MovimentacaoInstrumentoDTO.cs
- Codigo/Core/Service/IInstrumentoMusicalService.cs
- Codigo/Core/Service/IMovimentacaoInstrumentoService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/_TabelaMovimentacao.cshtml
- Codigo/Service/InstrumentoMusicalService.cs
- Codigo/Service/MovimentacaoInstrumentoService.cs
- Notificações via e-mail de instrumentos
- Adicionado validações para movimentação instrumento
- Melhoria nas consultas de instrumento
- Instrumento emprestado sendo novamente emprestado sem antes haver devolução
- Consulta de movimentação retornava todas as movimentações, agora retorna somente as movimentações para aquele instrumento
- Instrumentos danificados não são mais possíveis de serem emprestados
Adicione ou atualize um associado com um e-mail válido, então, faça um empréstimo ou devolução de instrumento e confira o seu e-mail.
> Notificações via e-mail de empréstimo e devolução de instrumentos e resolução de bugs

- Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Create.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Delete.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Details.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Edit.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Index.cshtml
refactor: traducao botoes e textos de Delete.cshtml
refactor: traducao botoes e textos de Index.cshtml
refactor: traducao botoes e textos de Create.cshtml
refactor: traducao botoes e textos de Edit.cshtml
refactor: traducao botoes e textos de Details.cshtml
> Traduções da views de UC- Manter ensaio

- Codigo/Email/Template/corpoEmailBatala.html
WEB Mobile
|---|
---
Desktop
|---|
> Template de envio de email feito.

- Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutColaborador.cshtml
- Codigo/GestaoGrupoMusicalWeb/wwwroot/css/headerLayout.css
> Layout criado

- Codigo/Core/Service/IInstrumentoMusicalService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
- Codigo/GestaoGrupoMusicalWeb/Models/InstrumentoMusicalViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Create.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Delete.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Details.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Edit.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Index.cshtml
- Codigo/Service/InstrumentoMusicalService.cs
* tradução/adaptação de textos das views
* Implementado o suficiente para produzir um selectlist para tipo de instrumento no create
* foi necessario implementar um metodo na service e interface para poder ter acesso aos tipos de instrumentos e nomes.
* Adicionado Display no model e criado atributo selectlist.
* Removido botão de "detalhes", pois não existe no protótipo.
> Tradução de Views e SelectList - Instrumento Musical

- Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
- Codigo/GestaoGrupoMusicalWeb/Models/PessoaViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Create.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Edit.cshtml
Implementacao de seleclist no campo isento pagamento e ativo em pessoa
refactor: das telas de edit e create foi adicionando um selectlist.
refactor: alem de deixar, já a implementacao da controller create com a mesma assinatura da IServicePessoa
> Implementacao de seleclist no campo isento pagamento e ativo em pessoa

- Codigo/Core/DTO/AssociadoDTO.cs
- Codigo/Core/DTO/PessoaDTO.cs
- Codigo/Core/Service/IPessoaService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Index.cshtml
- Codigo/Service/PessoaService.cs
- Criação do arquivo "PessoaDTO.cs".
- A interface do método GetAllDTO e a implementação da mesma.
- O código do método Index do arquivo "PessoaController.cs".
- Os ajustes da view Index da pasta Pessoa.
> Criação de PessoaDTO e uso da mesma na view Index

- Codigo/Core/Service/IPessoaService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
- Codigo/Service/PessoaService.cs
> Mudança de selectlist para PessoaService

- Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Create.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Edit.cshtml
- Id retirado da view create
- Id retirado da view edit
> Ids retirados de instrumento musical

- Codigo/GestaoGrupoMusicalWeb/Program.cs
refactor: alteracao na rotas da aplicacao, indo direto para home.
> refactor: alteracao na rotas da aplicacao, indo direto para home.

- Codigo/Core/Service/IPessoaService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/ColaboradorController.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Colaborador/Create.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Colaborador/Delete.cshtml
- Codigo/Service/PessoaService.cs
Nas controladoras(#129):
* Criada uma controladora apenas para colaborador
* Na controladora colaborador foi implementado os metodos de Create(Get/Post) e Delete(Get/Post)
Nas services(#130):
* Foram criados dois metodos (ToCollaborator e RemoveCollaborator)  
Nas Views(#131):
* Foram criadas/movidas duas views (Create e Delete) para colaborador
Vai ser necessário criar três botões na view de associado: uma para ver os detalhes, outra para promover a colaborador e outra para remover o cargo de colaborador. 
Ps. **_esses botões são apenas para testes_**
O que deve ser observado:
- se uma pessoa que é associado será promovido para colaborador.
- se uma cargo maior pode ser rebaixado a associado usando o botao para remover o cargo de colaborador.
- Por favor, prestar muita atenção em quem …
> Refatoração dao UC - Manter Colaborador

- Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
- Codigo/GestaoGrupoMusicalWeb/Models/PessoaViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Create.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Edit.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutColaborador.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutLogin.cshtml
- Codigo/GestaoGrupoMusicalWeb/wwwroot/lib/jquery-mask/jquery.inputmask.js
- adicionado regex no campos cep, cpf, email, telefone1 e telefone2
- adicionado máscara para os campos cpf, cep, telefone1 e telefone 2, ultilizando jquery.
- tratamento da mascara na controllerpessoa dos metodos edit e create post.
- adicionando pasta no wwwroot, que contém o código que gerar a máscara
> Refatorando a classe pessoaViewModel

- Codigo/GestaoGrupoMusicalWeb/Controllers/IdentityController.cs
- Codigo/GestaoGrupoMusicalWeb/Models/IdentityViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Models/PessoaViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Identity/Autenticar.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Identity/Cadastrar.cshtml
- Adicionado mascara em campo cpf na views autenticar e cadastrar
- Adicionado expressão regular para cpf na IdentyViewModel
> Adicionando mascara em campo cpf de autenticar e cadastrar

- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Create.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Edit.cshtml
- Refatorando selectlist da classe pessoa, deixando o select list padrão
1. campo isento de pagamento
2. campo Ativo
> Refatorando selectlist da classe pessoa

- Codigo/GestaoGrupoMusicalWeb/Controllers/GrupoMusicalController.cs
- Codigo/GestaoGrupoMusicalWeb/Models/GrupoMusicalViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Create.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Edit.cshtml
- Adicionados mascaras nos campos: cnpj, cep e telefone. Nas view de edit e create
- Feito o tratemento da mascara para cnpj e cep na controller de edit e create grupoMusical
> Adicionando mascaras nas views de grupoMusical

- Codigo/Core/Service/IMovimentacaoInstrumentoService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/BaseController.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Movimentar.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Shared/_Notificar.cshtml
- Codigo/Service/MovimentacaoInstrumentoService.cs
- Adicionado classe BaseController
- Adicionado Enum para tipos de notificações
- Adicionado partial View para exibição de notificações
- Adicionado método Notificar para notificar usuários
- Adicionado retornos numéricos para o create da classe MovimentacaoInstrumentoService
A classe BaseController será utilizada para substituir a herança default "Controller" nas Controllers. A BaseController possuí a implementação para as notificações, e agora é possível adicionar métodos/propriedades/classes globais que serão utilizados somente pelas Controllers.
Documentação do método está na interface pois o que utilizamos na controller é justamente a Interface, logo, o .NET exibe a descrição do método sobre a perspectiva da interface.
O texto exibido é exatamente o que está descrito na interface.
> Notificações de Sucesso/Alerta e Erro para Movimentação de Instrumento

- Codigo/Core/DTO/InformativoDTO.cs
- Codigo/Core/Service/IInformativoService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/HomeController.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/InformativoController.cs
- Codigo/GestaoGrupoMusicalWeb/Mapper/InformativoProfile.cs
- Codigo/GestaoGrupoMusicalWeb/Mapper/InformativoProfileDTO.cs
- Codigo/GestaoGrupoMusicalWeb/Models/InformativoViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Models/InformativoViewModelDTO.cs
- Codigo/GestaoGrupoMusicalWeb/Models/TelaPrincipalViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Program.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Home/Index.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Informativo/Create.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Informativo/Delete.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Informativo/Details.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Informativo/Edit.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Informativo/Index.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutColaborador.cshtml
- Codigo/Service/InformativoService.cs
Adição de informativo na home/index.
|---|
---
Criação do informativoDTO
|---|
Criação dos metodos: Create, Edit, Delete, Details, Index
|---|
> Implementação do UC_manter informativo

- Codigo/GestaoGrupoMusicalWeb/Views/Home/Index.cshtml
- Codigo/Service/EnsaioService.cs
- Codigo/Service/EventoService.cs
- Codigo/Service/InformativoService.cs
Botões de Ação de Ensaio e Evento da Home/index Com rotas.
> Adição de rotas da Home/index 

- Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Index.cshtml
[… ](refactor: alterando a responsividade da tabela de ensaio, adicionando flex-wrap) e outras classes do bootstrap. #175
> refactor: alterando a responsividade da tabela de enssaio

- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Index.cshtml
Tela Lista de associados
|---|
> Estilização da lista de associados

- Codigo/Core/Service/IPessoaService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Index.cshtml
- Codigo/Service/PessoaService.cs
**Oque foi feito :** 
> - Criação de um método para verificar se o CPF teve alguma alteração
> - E alteração da asp-action da index de Pessoa, foi alterado de Delete para RemoveAssociado
> Adição de método para validar o CPF quando for Editar a Pessoa

- Codigo/Core/DTO/EventoIndexDTO.cs
- Codigo/Core/Service/IEventoService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Evento/Index.cshtml
- Codigo/Service/EventoService.cs
###Feito a estilização da tela index de evento, o que foi feito:
-Adicionado botões na home
-Adicionado rota aos botões
-Tabela responsiva
> Estilização da tela index de evento

- Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Index.cshtml
**Oque foi feito**
> a estilização da tela index do grupo musical
> Tela index do Grupo Musical finalizada

- Codigo/Core/Service/IPessoaService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Create.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Index.cshtml
- Codigo/Service/PessoaService.cs
- Adicionado notificação de sucesso, quando adicionar um associado. 
- Adicionado notificação de alert, para campos de Data de Entrada e Data de Nascimento.
- Adicionado notificação de erro servidor
- código 200, adicionar uma pessoa
- código 400, Data de entrada fora do escopo
- código 401, Data de nascimento fora do escopo
- código 500, aconteceu algo ao servidor
- Adicionar um associado e testar, o cadastro normal.
- Adicionado um associado com o campo data de entrada preenchido e data de nascimento não preenchido
- Adicionado um associado com o campo data de nascimento preenchido e data de entrada não preenchido
- Tentar adicionar um associado com o campo data de entrada preenchido mas com um valor fora do escopo(uma data futura) e data de nascimento não preenchido
- Tentar adicionar …
> Notificações tela de adicionar associado

- Codigo/GestaoGrupoMusicalWeb/Controllers/GrupoMusicalController.cs
- Codigo/GestaoGrupoMusicalWeb/Models/GrupoMusicalViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Edit.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Index.cshtml
- Implementação da notificação de sucesso ao editar os dados de um grupo musical.
> Notificações - Edit - UC-Manter Grupo Musical

- Codigo/GestaoGrupoMusicalWeb/Models/PessoaViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Evento/Index.cshtml
- Foi modificado também a mensagem de validacao da pessoaViewModel do campo email, a pedido de @lauro-ss
> Alinhado o cabecalho da tabela de eventos

- Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Create.cshtml
> Estilização da View Create do UC InstrumentoMusical 

- Codigo/GestaoGrupoMusicalWeb/Models/AdministradorGrupoMusicalViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/AdministradorGrupoMusical/_Create.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Create.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Edit.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Identity/Autenticar.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Identity/Cadastrar.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Create.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Edit.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutAdmSistema.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutColaborador.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutLogin.cshtml
- Codigo/GestaoGrupoMusicalWeb/wwwroot/js/Mascara.js
- refatorado os lugares que tinha o codigo do javascript na tela
- Adicionado o arquivo Mascara.js, que contém as implementações das mascaras
- Adicionado o script do arquivo mascara.js nos layout
> Refatoração do script de mascara de javascript

- Codigo/Core/Service/IPessoaService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
- Codigo/Service/PessoaService.cs
- Adicionado notificação de delete em associado
> Adicionado notificação de delete em associado

- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Create.cshtml
2560px
|---|
---
1440px
|---|
---
1024px
|---|
---
768px
|---|
---
425px
|---|
---
375px
|---|
---
320px
|---|
---
> Criação da recursividade para o cadastro do associado

- Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Edit.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Index.cshtml
- Todo o código usado para criação das notificações da view Edit e Delete.
Para saber detalhes sobre as notificações criadas [clique aqui](https://github.com/marcosdosea/GestaoGrupoMusical/issues/209).
> UC-Manter Instrumento Musical - Notificação - view Edit e Delete

- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Create.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Edit.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutColaborador.cshtml
- Codigo/GestaoGrupoMusicalWeb/wwwroot/js/BuscaCep.js
-### O que foi feito
- Adicionado arqui javascript com a busca cep
- Refatorado as  views de associado create e edit. Foi feito adicionamento do id para passar valores para a view
> Busca cep adicionado ao associado

- Codigo/GestaoGrupoMusicalWeb/Views/Evento/Create.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Create.cshtml
**Imagens do que foi feito 
**
**Tela celular para instrumento
**
> Feita a estilização do Create de Evento e responsividade de instrumento para celular

- Codigo/GestaoGrupoMusicalWeb/Models/GrupoMusicalViewModel.cs
> Adição de mensagem de erro para o campo Estado de grupoMusical

- Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Create.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Edit.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutAdmSistema.cshtml
2560px
|---|
---
1440px
|---|
---
1024px
|---|
---
768px
|---|
---
425px
|---|
---
375px
|---|
---
320px
|---|
---
> Estilização do cadastro e edição das view de grupo musical 

- Codigo/GestaoGrupoMusicalWeb/Models/GrupoMusicalViewModel.cs
> Adição das validações  stringLength e placeholder para grupoMusical

- Codigo/GestaoGrupoMusicalWeb/Controllers/IdentityController.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
- Codigo/GestaoGrupoMusicalWeb/Models/IdentityViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Program.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Identity/Autenticar.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Identity/ForgotPassword.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Identity/PasswordChanged.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Identity/ResetPassword.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutLogin.cshtml
- Codigo/GestaoGrupoMusicalWeb/wwwroot/css/site.css
- Codigo/GestaoGrupoMusicalWeb/wwwroot/js/site.js
- Codigo/Service/PessoaService.cs
Apesar da issue ser apenas para o envio de email de adm de grupo musical eu acabei criando a funcionalidade de redefinição de senha geral (esqueci senha).
* Criados métodos na controller: ForgotPassword(GET/POST), ResetPassword(GET/POST) e PasswordChanged (IdentityController.cs)
* Criadas 3 Views para os novos metodos (Identity)
* Criados 2 models para ForgotPassword e ResetPassword (IdentityViewModel)
* Configuração para que o token criado para alteração da senha seja criado (Program.cs)
* Definição de vida do token para 2 horas após gerado (Program.cs)
* Criado uma classe para definir o cursor como hand (site.css)
* Alterado local de remoção de caracteres especiais em pessoaController para a service. Afim de evitar repetição de código e problema ao utiliza-los a partir de outras …
> Criada funcionalidade para enviar email de redefinição de senha ao criar/add um adm de grupo musical

- Codigo/Core/Service/IPessoaService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/AdministradorGrupoMusicalController.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/HomeController.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/IdentityController.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
- Codigo/GestaoGrupoMusicalWeb/Models/PessoaViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Colaborador/Create.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Colaborador/Delete.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Movimentacoes.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Create.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Delete.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Details.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Edit.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Index.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutAssociado.cshtml
- Codigo/Service/PessoaService.cs
- Cadastro identity de Associado
- Envio de e-mail com login e senha
- Layout associado
- Remoção de IdGrupoMusical e IdPapelGrupo de cadastro Associado
- Autenticar no sistema como Administrador do Grupo (Se não possuir cadastro para Adm Grupo, criar utilizando Adm Sistema)
- Clicar no menu lateral na opção "Associado"
- Cadastre um Associado utilizando um e-mail existente (para você receber o login e senha, por enquanto a senha é sempre o CPF)
- Se tudo ocorreu com sucesso, acesse o sistema utilizando o CPF e a senha recebidas pelo e-mail.
- Verifique o Layout é o de Associado
> Adicionado cadastro identity para Associado e Layout Associado

- Codigo/GestaoGrupoMusicalWeb/Controllers/AdministradorGrupoMusicalController.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/BaseController.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/IdentityController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/AdministradorGrupoMusical/Index.cshtml
* O metodo que cria token, gera a url e envia tudo por email para o usuario foi refatorado para a baseController
> Refatoração do metodo que cria token para redefinição de senha

- Codigo/Core/Service/IGrupoMusicalService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Evento/Create.cshtml
- Codigo/Service/GrupoMusicalService.cs
**Oque foi feito:**
- > Criação de um método (GetByIdGrupo) para retornar o id do grupo que o administrador do grupo esteja logado
- > Remoção da div que estava o campo idgrupomusical na View 
**Sugiro criar um novo grupo musical e adicionar uma administrador a ele para testar!**
> Remoção do campo IdGrupoMusical da tela Create de Evento 

- Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
> Mudança do modo de exibição da data exibindo sem a hora

- Codigo/Core/Service/IPessoaService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/AdministradorGrupoMusicalController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/AdministradorGrupoMusical/Index.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/AdministradorGrupoMusical/_Create.cshtml
- Codigo/Service/PessoaService.cs
- Adicionado notificação para Cadastro de adm grupo musical
- Consertado falha na função de AddAdmGrupo(), onde não tinha o tratamento da máscara de cpf, sendo assim a consulta não retornava nada
> Adicionado notificação para cadastro de adm grupo musical

- Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Evento/Edit.cshtml
**Oque foi feito:**
- > Mudei de selectlist para input hidden na view Edit de Evento
> Removendo o idGrupoMusical da View Edit de Evento 

- Codigo/Core/Service/IGrupoMusicalService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Evento/Edit.cshtml
- Codigo/Service/GrupoMusicalService.cs
> Adição de estilo em Edit de Evento concluída 

- Codigo/Core/Service/IPessoaService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
- Codigo/Service/PessoaService.cs
* Foi criado um metodo na service que retorna todos os associados do mesmo grupo musical do usuario identity autenticado.
* Alterado metodo da index de pessoa/associado
> Criado metodo que retorna lista com todos os associados de um mesmo Grupo Musical

- Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Details.cshtml
- Colocado design system de grupo musical na view de detalhes
> Details grupo musical

- Codigo/Core/Service/IInstrumentoMusicalService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
- Codigo/Service/InstrumentoMusicalService.cs
**Oque foi feito:**
- > Alteração na assinatura do método GetAllDTO de instrumento musical agora esta passando o id do grupo nele
> Feita alteração no código para mostrar os instrumentos de um determinado grupo musical

- .github/pull_request_template.md
Foi criado um pull request para usar como template ou abrir um PR. Basta seleciona-lo na hora de abrir o PR.
> Criado um template para Pull Request

- .github/pull_request_template.md
</div>
**Certifique-se de revisar o código e testar as alterações localmente antes de solicitar o merge.**
> Update ultima linha pull_request_template.md

- Codigo/GestaoGrupoMusicalWeb/Controllers/HomeController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Home/Index.cshtml
Verificar o código responsável por redirecionar o ADMINISTRADOR GRUPO para a Index da controller de Instrumento Musical.
Para mais detalhes sobre o problema [clique aqui](https://github.com/marcosdosea/GestaoGrupoMusical/issues/267).
> Remoção dos botões "Novo..." da homepage

- Codigo/Core/DTO/InstrumentoAssociadoDTO.cs
- Codigo/Core/Service/IMovimentacaoInstrumentoService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Movimentacoes.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/_TabelaDevolucoesAssociado.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/_TabelaEmprestimosAssociado.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/_TabelaMovAssociado.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutAssociado.cshtml
- Codigo/GestaoGrupoMusicalWeb/wwwroot/js/modal.js
- Codigo/Service/MovimentacaoInstrumentoService.cs
- DTO Para tabela de minhas movimentações
- Método Post para confirmar empréstimo/devolução
- Estilização da tabela
- Notificações
- Acesse com um perfil de adm grupo musical (se não possuir crie um)
- Crie um Associado com um e-mail válido para você receber a senha
- Acesse o sistema como um Associado em uma Aba Anônima ou em outro navegador
- Realize um empréstimo para o Associado que acabou de cadastrar
- No outro navegador com acesso de Associado, visualize a movimentação e clique em "Confirmar"
- Realize uma devolução para o mesmo Associado
- Confirme a devolução
- Teste quantas vezes desejar
> Adicionado confirmar empréstimo/devolução de instrumento para Associado

- Codigo/Core/Service/IPessoaService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
- Codigo/Service/PessoaService.cs
</div>
Fazer uma restrição para o SelecList, que deveria retornar apenas associados e ordenado por nomes e que estejam ativos.
Ao movimentar o instrumento, quando for selecionar o associado, checar se esta em ordem, indico associar pelo menos uns 5 associados com nomes de inicias diferentes e de maneira aleatória.
> Feita restrição de associado e ordenação em ordem alfabética 

- Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
- Codigo/Service/PessoaService.cs
</div>
Resolvido bug de Edit associado
- Edite um associado
> Resolvido bug de Edit associado

- Codigo/Core/DTO/UserDTO.cs
- Codigo/Core/Service/IPessoaService.cs
- Codigo/GestaoGrupoMusicalWeb/Helpers/ApplicationUserClaims.cs
- Codigo/GestaoGrupoMusicalWeb/Program.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutAdmSistema.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutAssociado.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutColaborador.cshtml
- Codigo/Service/PessoaService.cs
</div>
Adicionado nome de usuário e papel ao layout
- Acesse os perfis e verifique o nome e papel
> Adicionado nome de usuário logado ao Layout

- Codigo/Core/Service/IPessoaService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/AdministradorGrupoMusicalController.cs
- Codigo/Service/PessoaService.cs
</div>
Envio de email para redefinição de senha apenas quando o associado não existir no banco.
* O teste será, resumidamente, através das notificações e do email.
1. Tente registrar um adm de grupo que não possui cadastro ainda
- Se receber a notificação de sucesso verifique se receberá o email para redefinir senha.
2. Já possuindo um usuario cadastrado e ele não sendo adm de grupo ainda
- Receberá apenas uma notificação de sucesso e não deve receber email para redefinir senha. 
3. Tente registrar um adm que já é adm.
- Notificação de erro.
4. Tente registrar alguém de outro grupo musical
> Definido envio de email para redefinição de senha apenas para novo usuário

- Codigo/Core/Service/IPessoaService.cs
- Codigo/Service/PessoaService.cs
</div>
Gerar senha aleatória ao criar user identity
Criar um usuário que ainda não existia no sistema e tentar autenticar da forma anterior(cpf e cpf).
Obs: se quiser verificar qual a senha que foi colocada precisa alterar localmente o metodo que envia notificação contendo a senha e usuario.
> Criado método para gerar senha aleatória para user identity

- Codigo/GestaoGrupoMusicalWeb/Controllers/GrupoMusicalController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Delete.cshtml
Adicionar input type hidden no campo CNPJ na view delete de Grupo Musical, Corrigir mensagem de erro de exclusão de grupo musical.
</div>
Adicionado um input  type hidden na view delete de grupo musical.
Correção da mensagem de erro de exclusão de grupo musical.
Tentar excluir um grupo musical que tem associado vinculado.
> Adicionar input type hidden no campo CNPJ na view delete de Grupo Musical, Corrigir mensagem de erro de exclusão de grupo musical.

- Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
</div>
Add role Associado para ConfirmarMovimentacao
> Add role Associado para ConfirmarMovimentacao

- Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Index.cshtml
</div>
Como alterações foram visual, sõ olha a tela
> refactor: tirando o justify, alinhando os itens

- Codigo/GestaoGrupoMusicalWeb/Controllers/IdentityController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Identity/Autenticar.cshtml
- Codigo/Service/PessoaService.cs
</div>
Adicionando notificações de alerta no autenticar, para quando o usuário colocar a senha incorreta ou não existe no sistema
-Colocar o cpf de um associado que existe no sistema, mas a senha inválida
-Colocar o cpf de um associado que não existe no sistema
Print do cpf que existe no sitema, mas a senha inválida
Print do cpf que não existe no sistema
> Adicionando notificacoes de alerta no autenticar

- Codigo/Core/Service/IInstrumentoMusicalService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Delete.cshtml
- Codigo/Service/InstrumentoMusicalService.cs
</div>
Adicionar notificações ao deletar instrumento
- Excluir um instrumento musical
> Adicionado notificações ao deletar instrumento

- Codigo/Core/Service/IPessoaService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/AdministradorGrupoMusicalController.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
- Codigo/GestaoGrupoMusicalWeb/Program.cs
- Codigo/Service/PessoaService.cs
</div>
Tornar email unico e impedir cadastro com mesmo email.
Tente cadastrar dois associados/adm com um mesmo email.
> Tornando email unico no identity e validando no código

- Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Create.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Edit.cshtml
- Codigo/GestaoGrupoMusicalWeb/wwwroot/js/Mascara.js
</div>
Validação do CPF para as views de grupo mujsical quando o atributo que define a chave pix for setado.
Só é adicionar o tipo da chave pix de CPF e testar com CPF válido e outro inválido
> Validação de CPF para views de grupo musical.

- Codigo/Core/Service/IMovimentacaoInstrumentoService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/_TabelaMovimentacao.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutColaborador.cshtml
- Codigo/Service/MovimentacaoInstrumentoService.cs
</div>
Adicionado uso do modal para Excluir e Notificar movimentação e Restringir envio de e-mail
- Empreste/Devolva um Instrumento para algum Associado com e-mail existente
> Adicionado uso do modal para Excluir e Notificar movimentação e Restringir envio de e-mail

- Codigo/GestaoGrupoMusicalWeb/Models/PessoaViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/RemoveAssociado.cshtml
</div>
Estilizar tela de remover associado 
> Aplicar Design System na tela remover associado 

- Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
</div>
Cadastre um associado com um email que você tenha acesso e verifica se chega o email para redefinir a senha.
> Enviando email para redefinir senha do associado. #337

- Codigo/Core/DTO/UserDTO.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/HomeController.cs
- Codigo/GestaoGrupoMusicalWeb/Helpers/ApplicationUserClaims.cs
- Codigo/Service/PessoaService.cs
</div>
Proibir associado com status ativo=não de autenticar
- Altere um associado para Ativo = Não
- Tente se autenticar como esse associado
- Verifique se o sistema bloqueou a login
- Altere o mesmo associado para Ativo = Sim
- Tente se autenticar como esse associado
- Verifique se o sistema liberou o login
> Proibir associado com status ativo=não de autenticar

- Codigo/GestaoGrupoMusicalWeb/Views/AdministradorGrupoMusical/_TabelaAdministrador.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutAdmSistema.cshtml
- Codigo/Service/PessoaService.cs
</div>
Foi solicitado um pop-up para remorção de cargo de adm para associado
Somente clicar nos botões excluir e notificar.
> Adicionando Modal para excluir e notificar da view index de administrador de grupo musical. resolve #323

- Codigo/Core/Service/IPessoaService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/HomeController.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/IdentityController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Index.cshtml
- Codigo/Service/PessoaService.cs
</div>
1 - Alterar atributo ATIVO para SIM ao alterar senha de associado.
2 - Bug que adm de sistema nao podia autenticar.
* 1 - Cadastre um ASSOCIADO, altere a senha através do link enviado pro email usado no cadastro e tente autenticar com o login dele. Se:
Logar: ok.
!Logar: erro erro formata
* 2 - Depois de testar o primeiro passo: desativar o associado através de um adm de grupo musical e tente autenticar novamente como o associado que foi desativado. Se não autenticar está correto, mas tente alterar a senha dele e autenticar (como ao redefinir senha ele ativa o associado é bom verificar se a nova correção está funcionando).
* 3 - Tente autenticar como adm de sistema e caso não autentique não está funcionando.
**Certifique-se de revisar o …
> Alterar Status Ativo de Associado Ao Alterar Senha e Resolvido Bug com Login ADM Sistema

- Codigo/Service/PessoaService.cs
</div>
Corrigir bug que nao ativa associado ao redefinir a senha.
adicione um associado, mude a senha dele e tente autenticar para verificar se esta funcionando corretamente.
> Correção ao ativar associado. #345

- Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Details.cshtml
- Codigo/GestaoGrupoMusicalWeb/wwwroot/css/site.css
…e.css e remorção do form-select do campo tipo da chave pix. resolve #350
</div>
Foi feito o design system para view details de grupo musical
So visitar a view details de grupo musical.
> Aplicação do design system da view details de grupo musical.

- Codigo/GestaoGrupoMusicalWeb/Views/Figurino/Create.cshtml
</div>
Adicionar o design system a view de cadastro de figurino
So visitar a view create de figurino
> Adicionar o design system a view de cadastro de figurino

- Codigo/GestaoGrupoMusicalWeb/Views/Figurino/Edit.cshtml
</div>
Estilização da view edit de figurino
Visitar a view edit de figurino
> Estilização da view edit de figurino.

- Codigo/GestaoGrupoMusicalWeb/Views/Figurino/Index.cshtml
</div>
Adição de um modal para excluir um figurino
Pressionar o botão excluir
> Adição de modal para excluir figurino.

- Codigo/GestaoGrupoMusicalWeb/Models/EnsaioViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Create.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutColaborador.cshtml
</div>
Criação da view create de ensaio
Visitar a view de cadastro de ensaio.
> Aplicar Design System view Create de ensaio

- Codigo/GestaoGrupoMusicalWeb/Controllers/AdministradorGrupoMusicalController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/AdministradorGrupoMusical/Index.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/AdministradorGrupoMusical/_Create.cshtml
</div>
Só cadastrar um novo adm para grupo musical
> Removendo redirecionar

- Codigo/GestaoGrupoMusicalWeb/Views/Informativo/Index.cshtml
</div>
Estilizar a index de informativo
> Feita a estilização da index de informativo

- Codigo/Core/DTO/EstoqueDTO.cs
- Codigo/Core/Service/IFigurinoService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/FigurinoController.cs
- Codigo/GestaoGrupoMusicalWeb/Mapper/EstoqueDTOProfile.cs
- Codigo/GestaoGrupoMusicalWeb/Models/EstoqueDTOViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Figurino/Estoque.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Figurino/Index.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Figurino/_TabelaEstoque.cshtml
- Codigo/Service/FigurinoService.cs
</div>
entrando em estoque e verificando se tem os dados cadastrados
> Criação do estoque de figurino

- Codigo/Core/Service/IFigurinoService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/FigurinoController.cs
- Codigo/GestaoGrupoMusicalWeb/Mapper/EstoqueDTOProfile.cs
- Codigo/GestaoGrupoMusicalWeb/Models/EstoqueDTOViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Models/EstoqueViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Figurino/CreateEstoque.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Figurino/Estoque.cshtml
- Codigo/Service/FigurinoService.cs
</div>
Implementação de criação de figurino
Acesse como adm de grupo e remexa de todo jeito criando estoques de um figurino.
> Create para Estoque de Figurino

- Codigo/Service/MovimentacaoFigurinoService.cs
</div>
ao criar um movimento de figurino nao era alterado o atributo "entregue" do estoque.
Movimentar figurino entregando, devolvendo e verificando o atributo "Entregue" em estoques
> Correção de atributo "Entregue" ao movimentar figurino

- Codigo/GestaoGrupoMusicalWeb/Views/Figurino/Movimentar.cshtml
> Resolução do bug de figurino com CheckBox de Danificado marcado

- Codigo/Core/Service/IEnsaioService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
- Codigo/Service/EnsaioService.cs
</div>
Adicionar o id do grupo musical na index 
> Adicionando o IdGrupoMusical na index de Ensaio

- Codigo/GestaoGrupoMusicalWeb/Views/Figurino/Index.cshtml
</div>
Colocar a view Index de Figurino nos padrões do design system do projeto Batalá.
Faça login no sistema como Administrador do sistema. Após isso, clique no menu e selecione a opção Figurinos. 
> Index - Figurinos - Design System

- Codigo/GestaoGrupoMusicalWeb/wwwroot/css/site.css
</div>
campo type read-only e disabled  mudança na cor do campo e muda o tipo do cursor.
Visitar uma view que tem os campos type disabled ou read-onlyu
> Alteração feita para o campo type read-only e disabled juntamente com a mudança do cursor.

- Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Create.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Evento/Create.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Informativo/Create.cshtml
</div>
Mudança na rota de `Ensaio`, `Evento` e `Informativo`, todas rotas da views `create` referente ao botão `voltar` para `Home/index`
Entrar em uma dessas views `create` e `Pressionar` o botão `Voltar`
> Mudança na rota de Ensaio, Evento e Informativo, todas rotas da views create referente ao botão voltar para Home/index

- Codigo/Core/DTO/MovimentacaoAssociadoFigurinoDTO.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Figurino/_TabelaDevolucaoFigurino.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Figurino/_TabelaFigurinoEntregue.cshtml
</div>
-Entrar como associado em figurinos
> Adicionado design system a tela de movimentações do associado

- Codigo/GestaoGrupoMusicalWeb/Views/Figurino/CreateEstoque.cshtml
</div>
Estilizado view novo estoque
-Entrar como adm do grupo e verificar a tela de novo estoque
> Estilizado view novo estoque

- Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
- Codigo/GestaoGrupoMusicalWeb/Models/MovimentacaoInstrumentoViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Movimentar.cshtml
</div>
Alterar a view para remover o selectlist e pegar o nome do associado 
Movimentando instrumento para associados que já estão associado em um instrumento 
Antes
Depois 
> Alteração de SelecctList para label para associado que já tenha movimentação com um instrumento

- Codigo/GestaoGrupoMusicalWeb/Views/Figurino/EditEstoque.cshtml
</div>
Estilizar view edit de estoque
-Só entrar como adm do grupo, e em figurinos > estoque > editar
> Estilizado view edit estoque.

- Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
</div>
O select list não estava sendo chamado, caso a operação de adicionar associado desse erro. ou seja, estava passando o select list "null"
-Cadastrar um associado, mas tentar aplicar erro nos campos. "Como email existente" ou uma "data futura na data de nascimento". O resultado o select list deve vim preenchido
> [Bug] No select list para "Tamanho de Roupa" no cadastro de associado

- Codigo/ServiceTests/MovimentacaoFigurinoServiceTests.cs
</div>
Criação dos testes de unidade de MovimentacaoFigurino.
Criação do métodos de testes:
Faça o seguinte passo a passo: Visual Studio -> Test -> Test Explorer -> Service.Tests -> MovimentacaoFigurinoServiceTests -> Run (
). 
**Observação:** avalie o código do testes.
**Resultado dos testes**
> Teste de Unidade - MovimentacaoFigurino - Service

- Codigo/GestaoGrupoMusicalWeb/Controllers/FigurinoController.cs
- Codigo/GestaoGrupoMusicalWeb/Models/MovimentacaoFigurinoViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Figurino/Movimentar.cshtml
- Codigo/Service/MovimentacaoFigurinoService.cs
</div>
Remover opção de marcar danificado
Remoção:
ao movimentar instrumento marcar a opção "Devolver" e verificar se aparece o checkbox para danificado.
> Removida opção de danificado ao movimentar figurino

- Codigo/GestaoGrupoMusicalWeb/Views/Figurino/_TabelaEstoque.cshtml
</div>
Adicionar rota para o botão de editar  estoque, na view _TabelaEstoque
-Logar como admGrupoMusical, entrar e figurino > estoque e testar o botão editar 
> refactor: adicionando rotar para o botão de edit estoque. #451

- Codigo/Core/DTO/EstoqueDTO.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/FigurinoController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Figurino/Estoque.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Figurino/_TabelaEstoque.cshtml
</div>
Adicionar atributo quantidade descartada ao estoque
Verificar operações com estoque
> Adicionado Novo Atributo Ao Estoque

- Codigo/Core/Service/IFigurinoService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/FigurinoController.cs
- Codigo/Service/FigurinoService.cs
</div>
Substituição dos números "mágicos" por outro tipo de retorno.
Realizar todas as operações dos métodos que foram alterados e verificar consistência dos tipos de retorno com os cases do switch.
MICROSOFT. System.Net.HttpStatusCode Class (System.Net). Disponível em: https://learn.microsoft.com/pt-br/dotnet/api/system.net.httpstatuscode?view=net-7.0. 
> Alterado Tipo de Retorno dos Métodos de UC - Manter Figurino

- Codigo/Core/DTO/EnsaioDTO.cs
- Codigo/Core/Service/IEnsaioService.cs
- Codigo/Core/Service/IPessoaService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
- Codigo/GestaoGrupoMusicalWeb/Models/EnsaioViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Create.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Edit.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Shared/_AutoCompleteCssPartial.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Shared/_AutoCompletePartial.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Shared/_EnablePopoversPartial.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutColaborador.cshtml
- Codigo/GestaoGrupoMusicalWeb/wwwroot/js/autoComplete.js
- Codigo/GestaoGrupoMusicalWeb/wwwroot/js/enablePopovers.js
- Codigo/GestaoGrupoMusicalWeb/wwwroot/lib/jquery-autocomplete/code.jquery.com_ui_1.13.2_jquery-ui.js
- Codigo/GestaoGrupoMusicalWeb/wwwroot/lib/jquery-autocomplete/code.jquery.com_ui_1.13.2_themes_base_jquery-ui.css
- Codigo/Service/EnsaioService.cs
- Codigo/Service/PessoaService.cs
</div>
Atualizar cadastro de Ensaio
- Cadastre alguns regentes e associados no sistema e então crie um ensaio.
`
INSERT INTO PESSOA VALUES (null,12345678940,"Reinan Associado","M","49530000","Rua das Flores","Centro",
"Ribeirópolis","SE",null,"Sem telefone",null,"lauroteste@email.com",null,null,
null,1,0,1,1,3);
INSERT INTO PESSOA VALUES (null,12345678941,"Gabriel Associado","M","49530000","Rua das Flores","Centro",
"Ribeirópolis","SE",null,"Sem telefone",null,"lauroteste@email.com",null,null,
null,1,0,1,1,3);`
`INSERT INTO PESSOA VALUES (null,12345678940,"Mosis Regente","M","49530000","Rua das Flores","Centro",
"Ribeirópolis","SE",null,"Sem telefone",null,"lauroteste@email.com",null,null,
null,1,0,1,5,3);
INSERT INTO PESSOA VALUES …
> Atualizar cadastro de Ensaio

- Codigo/GestaoGrupoMusicalWeb/Controllers/FigurinoController.cs
- Codigo/GestaoGrupoMusicalWeb/GestaoGrupoMusicalWeb.csproj
- Codigo/GestaoGrupoMusicalWeb/Views/Figurino/_TabelaMovimentacao.cshtml
</div>
Paginação da tela de movimentação figurino #454 
Entrar como adm do grupo e testar os filtros e a paginação, de acordo com as movimentações figurino. 
> Paginação da tela de movimentação figurino #454

- Codigo/Service/PessoaService.cs
</div>
Promover ROLE no User Identity ao Adicionar Colaborador
Adicionar um perfil de associado como colaborador ou regente e autenticar com o perfil dele para verificar se de fato foi alterado a role identity dele. Além disso, verificar no banco de dados as entidades referentes as roles e a userroles para verficiar se de fato foi alterado.
> Promover ROLE no Identity ao Adicionar Colaborador

- Codigo/Core/Service/IGrupoMusicalService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/AdministradorGrupoMusicalController.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/GrupoMusicalController.cs
- Codigo/GestaoGrupoMusicalWeb/Models/GrupoMusicalViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/IndexAdmGrupo.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/_EditAdmGrupo.cshtml
- Codigo/Service/GrupoMusicalService.cs
</div>
Adição de Funcionalidade para Editar Grupo Musical através de perfil de administrador de grupo.
tentar editar grupo musical pelo perfil de administrador de grupo
> Adição de Funcionalidade para Editar Grupo Musical

- Codigo/Core/Service/IInstrumentoMusicalService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
- Codigo/Service/InstrumentoMusicalService.cs
</div>
Alterar retornos de inteiro por HttpStatusCode em UC - InstrumentoMusical
-Só entrar como adm grupo musical e testar as notificações para edit, create e delete
> Alterar retornos de inteiro por HttpStatusCode em UC - InstrumentoMusical

- Codigo/Service/PessoaService.cs
</div>
Revogar direitos de roles de colaborador/regente do user identity
Adicione um colaborador, verifique se o perfil dele de fato ficou como colaborador/regente e depois exclua-a como colaborador. Além disso, verificar no banco de dados as entidades referentes as roles e a userroles para verficiar se de fato foi alterado.
> Adição e remoção de roles ao user identity no metodo RemoveCollaborator

- Codigo/Core/Service/IGrupoMusicalService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/FigurinoController.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/GrupoMusicalController.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
- Codigo/Service/GrupoMusicalService.cs
</div>
Alterar números "mágicos" por HttpStatusCode
Fazer todas as operações de grupo musical que envolvem: Create, Edit, Delete.
> Alterar Retornos de UC - Manter Grupo Musical

- Codigo/Core/Service/IMovimentacaoFigurinoService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/FigurinoController.cs
- Codigo/Service/MovimentacaoFigurinoService.cs
</div>
Alterar retornos de UC Manter movimentação figurino
fazendo operações referentes ao caso de uso.
> Alterar Retornos de UC - Movimentação Figurino

- Codigo/Core/DTO/EnsaioDTO.cs
- Codigo/Core/DTO/EnsaioFrequenciaDTO.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Details.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/RegistrarFrequencia.cshtml
- Codigo/Service/EnsaioService.cs
</div>
Atualizar consulta de regentes para lista de frequência de ensaio e details
- Cadastre um Ensaio
- Consulte a lista de frequência para ver os regentes
- Consulte o detalhes para ver os regentes
> Atualizar consulta de regentes para lista de frequência de ensaio e details

- Codigo/Core/Service/IMovimentacaoInstrumentoService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/AdministradorGrupoMusicalController.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/FigurinoController.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/GrupoMusicalController.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/IdentityController.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
- Codigo/Service/MovimentacaoInstrumentoService.cs
</div>
Alteração de retorno de números "mágicos" para HTTPSTATUSCODE.
Fazer todas as operaçções referente a movimentar instrumento e tentar forçar erros.
> Alterar Retornos de UC - Movimentação Instrumento

- Codigo/Core/Service/IEnsaioService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
- Codigo/Service/EnsaioService.cs
</div>
alteração de retornos do manter ensaios.
Fazer todas as operaçções referente a ensaio e tentar forçar erros.
> Alterar Retornos de UC - Manter Ensaio

- Codigo/GestaoGrupoMusicalWeb/Controllers/FigurinoController.cs
</div>
Adição de todas as Roles identity para Manter Figurino incluindo a movimentação de instrumento
Verificar se está tudo funcionando normalmente. Para testar mesmo só após fazer o layout para colaborador poder usar as funcionalidades.
> Adição de todas as Roles identity para Manter Figurino

- Codigo/GestaoGrupoMusicalWeb/Controllers/FigurinoController.cs
</div>
Correção de identação e remoção de namespace redundante.
> Indentação, Remoção de namespace redundante e adição de roles

- Codigo/Core/Service/IEnsaioService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Edit.cshtml
- Codigo/GestaoGrupoMusicalWeb/wwwroot/js/autoComplete.js
- Codigo/Service/EnsaioService.cs
</div>
Atualizar o Edit de Ensaio
- Crie um ensaio
- Remova ou adicione outros regentes
> Atualizado o Edit de Ensaio

- Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
</div>
[Adição de todas as Roles identity para Manter Ensaio](https://github.com/marcosdosea/GestaoGrupoMusical/issues/503)
Entrar como colaborador e como regente para verificar se tem acesso as funcionalidades de ensaio 
> Inserção das rules em ensaio 

- Codigo/GestaoGrupoMusicalWeb/Controllers/FigurinoController.cs
- Codigo/GestaoGrupoMusicalWeb/GestaoGrupoMusicalWeb.csproj
- Codigo/GestaoGrupoMusicalWeb/Views/Figurino/_TabelaMovimentacao.cshtml
</div>
Tirando a paginação que estava implementada, e dependência do projeto
-Entrar como adm do grupo, e entrar na tela de movimentação figurino. verificar se há paginação 
> Tirando a paginação que estava implementada, e dependência do projeto

- Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
</div>
refactor: inserindo roles nas funções, instrumento musical controller. #505 
-Entrar com um colaborador ou afm grupo musical, vericar se as roles estão corretas, de acordo com análise projeto no UML
> refactor: inserindo roles nas funções, instrumento musical controller

- Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
</div>
Adicionar a role para que o colaborador possa manter o associado 
Entrar como colaborador e fazer e adicionar usuários, editar, ver detalhes e remove-los 
> Adicionando Role Colaborador para poder manter um associado

- Codigo/GestaoGrupoMusicalWebTests/Controllers/ColaboradorControllerTests.cs
- Codigo/GestaoGrupoMusicalWebTests/Controllers/EnsaioControllerTests.cs
- Codigo/GestaoGrupoMusicalWebTests/Controllers/EventoControllerTests.cs
- Codigo/GestaoGrupoMusicalWebTests/Controllers/GrupoMusicalControllerTests.cs
- Codigo/GestaoGrupoMusicalWebTests/Controllers/InstrumentoMusicalControllerTests.cs
- Codigo/GestaoGrupoMusicalWebTests/Controllers/PessoaControllerTests.cs
- Codigo/ServiceTests/EnsaioServiceTests.cs
- Codigo/ServiceTests/EventoServiceTests.cs
- Codigo/ServiceTests/GrupoMusicalServiceTests.cs
</div>
comentar testes com erros
-Verificar se o projeto ainda está com erro em no projeto testes.
> refactor: comentando testes com erros

- Codigo/Core/DTO/UserDTO.cs
- Codigo/Core/Service/IPessoaService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/IdentityController.cs
- Codigo/GestaoGrupoMusicalWeb/Helpers/ApplicationUserClaims.cs
- Codigo/GestaoGrupoMusicalWeb/Mapper/UserProfile.cs
- Codigo/GestaoGrupoMusicalWeb/Models/UserSystemViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Models/UserViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Identity/Perfil.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Identity/PerfilSistema.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutAdmSistema.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutAssociado.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutColaborador.cshtml
- Codigo/GestaoGrupoMusicalWeb/wwwroot/js/site.js
- Codigo/Service/PessoaService.cs
</div>
Implementar menu "Meus Dados" para o usuário poder ver/editar suas infos
- Clique no nome do usuário no canto superior direito da tela
- Clique em "Meus Dados"
- Altere alguma informação e clique em Salvar
- Verifique se a informação foi alterada
> Implementado menu "Meus Dados" para o usuário poder ver/editar suas infos

- Codigo/Core/Service/IPessoaService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Index.cshtml
- Codigo/Service/PessoaService.cs
</div>
Desenvolver a paginação de associado usando o Datatable
Fazendo os mesmos procedimentos que faziam antes da paginação
> Paginação do Associado

- Codigo/GestaoGrupoMusicalWeb/wwwroot/css/site.css
</div>
Responsividade do dataTable.
Ir em algum dataTable e verificar a resposividade.
> Sunindo responsividade do dataTable

- Codigo/Core/Service/IFigurinoService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/FigurinoController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Figurino/Index.cshtml
- Codigo/Service/FigurinoService.cs
</div>
Paginação na index de figurino
Só logar como adm do grupo e testa a paginação na index figurino
> Paginacao em index Figurino

- Codigo/Service/EnsaioService.cs
</div>
Consertada funcionalidade exclusão de ensaio
-Entrar como adm do grupo e tentar, excluir um ensaio.
> Consertada exclusão de ensaio

- Codigo/Core/DTO/EnsaioIndexDTO.cs
- Codigo/Core/Service/IEnsaioService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Edit.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Index.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutColaborador.cshtml
- Codigo/Service/EnsaioService.cs
> Paginação em ensaio

- Codigo/Core/Core.csproj
- Codigo/Core/DTO/MaterialEstudoIndexDTO.cs
- Codigo/Core/Service/IMaterialEstudoService.cs
- Codigo/Core/Service/MaterialEstudoDTO.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/MaterialEstudoController.cs
- Codigo/GestaoGrupoMusicalWeb/GestaoGrupoMusicalWeb.csproj
- Codigo/GestaoGrupoMusicalWeb/Mapper/MaterialEstudoProfileIndexDTO.cs
- Codigo/GestaoGrupoMusicalWeb/Models/MaterialEstudoViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Models/MaterialEstudoViewModelDTO.cs
- Codigo/GestaoGrupoMusicalWeb/Views/MaterialEstudo/Index.cshtml
- Codigo/Service/MaterialEstudoService.cs
</div>
Adicionar view de index
Adicionar novo métodos de service.
Mexer na controller para trazer os dados
- View de index adicionado com sucesso.
- Novo método na service adicionado para trazer os dados.
- Controller alterada para trazer os ViewModel para a view.
- Foi necessário passar como parâmetro o grupoMusicalService na controller como injeção de dependência.
- Primeiro precisa inserir alguns dados no banco mySQL para testar o index e exibir a lista. Está aqui um exemplo de inserção:
INSERT INTO MATERIALESTUDO (nome,link,data,idGrupoMusical,idColaborador)
VALUES ("Videos no …
> Adicionado view de index.

- Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/MaterialEstudoController.cs
- Codigo/Service/MaterialEstudoService.cs
</div>
- Adição da funcionalidade de delete no Manter Material de Estudo.
- O que foi solicitado.
- Não houve mudanças errôneas.
> Branch vere material estudo delete 543

- Codigo/ServiceTests/MaterialEstudoServiceTests.cs
> Implementação material estudo service tests

- Codigo/Core/Core.csproj
- Codigo/Core/DTO/MaterialEstudoIndexDTO.cs
- Codigo/Core/Service/IMaterialEstudoService.cs
- Codigo/Core/Service/MaterialEstudoDTO.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/MaterialEstudoController.cs
- Codigo/GestaoGrupoMusicalWeb/GestaoGrupoMusicalWeb.csproj
- Codigo/GestaoGrupoMusicalWeb/Mapper/MaterialEstudoProfile.cs
- Codigo/GestaoGrupoMusicalWeb/Mapper/MaterialEstudoProfileIndexDTO.cs
- Codigo/GestaoGrupoMusicalWeb/Models/MaterialEstudoViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Models/MaterialEstudoViewModelDTO.cs
- Codigo/GestaoGrupoMusicalWeb/Program.cs
- Codigo/GestaoGrupoMusicalWeb/Views/MaterialEstudo/Edit.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/MaterialEstudo/Index.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutColaborador.cshtml
- Codigo/Service/MaterialEstudoService.cs
</div>
Foi solicitada a implementação da página de edição do caso de uso 'Material de Estudo'.
Adicione uma linha na tabela 'Material de Estudo' no próprio banco de dados. Em seguida, entre na página de 'Material de Estudo', acesse a opção 'Editar' e altere os dados para testar a página.
> 552 implementar material de estudo edit

- Codigo/Core/DTO/PessoaEnviarEmailDTO.cs
- Codigo/Core/Service/IGrupoMusicalService.cs
- Codigo/Core/Service/IMaterialEstudoService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/MaterialEstudoController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/MaterialEstudo/Index.cshtml
- Codigo/Service/GrupoMusicalService.cs
- Codigo/Service/MaterialEstudoService.cs
</div>
Criação do recurso de enviar notificação do material estudo através do botão de notificação.
Não houve mudanças, apenas acrescimento de código na Service, mas talvez dê conflito na classe.
Bastar inserir alguns materiais de estudo e depois ir para a tela de material de estudo e apertar no botão de Notificar.
> Notificação de Material Estudo foi finalizada 544

- Codigo/Core/Service/IInformativoService.cs
- Codigo/Service/InformativoService.cs
- Codigo/ServiceTests/InformativoServiceTests.cs
</div>
- Teste de Unidade InformativoService
Acessar a hierarquia de organização dos arquivos do sistema, localizar a pasta ServiceTest, clicar com o botão direito do mouse, em seguida escolher a opção **executar**.
> Branch gilmario teste unidade informativo service#372

- Codigo/Core/DTO/EventoIndexDTO.cs
- Codigo/Core/Service/IEventoService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
- Codigo/GestaoGrupoMusicalWeb/Models/EventoViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Evento/Index.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/MaterialEstudo/Index.cshtml
- Codigo/Service/EventoService.cs
</div>
- Padronização no layout de index, como aparecer notificação etc.
- Basta clicar em Eventos e Criar Eventos. O restante dos botões já funcionam normalmente como antes e o layout está padronizado, como por exemplo uma mudança de cores a cada eventol.
> Padronizado o layout de index de eventos para futuras edições.

- Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutColaborador.cshtml
</div>
- Exibir na lateral esquerda a opção **Inormativos**
Abrir o sistema na **Visão de Colaborador**, em seguida localizar no menu lateral esquerdo a opção **Informativos**, clicar na referida opção.
> Exibindo no menu lateral esquerdo a opção Informativos.

- Codigo/Core/DTO/MaterialEstudoDTO.cs
- Codigo/Core/Service/IMaterialEstudoService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/MaterialEstudoController.cs
- Codigo/GestaoGrupoMusicalWeb/Mapper/MaterialEstudoProfile.cs
- Codigo/GestaoGrupoMusicalWeb/Views/MaterialEstudo/Edit.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/MaterialEstudo/Index.cshtml
- Codigo/Service/MaterialEstudoService.cs
</div>
Index -> Data -> Apresentar data e hora
Index -> Por padrão, mostrar por ordem decrescente da data
Index -> Notificar -> Colocar um pop-up dizendo Sim ou Não para notificar
Edit -> Tirar o campo data; Editar vai pegar a data de agora na hora de editar no banco.
Novo Material Estudo -> No momento de inserir, notificar as pessoa.
Criei um DTO para a view de index levando apenas os dados necessários para evitar passar strings que não vão ser usadas pela rede, como o ID do colaborador e o ID do grupo musical. (id do grupoMusical a gente já pega com o token de autenticação).
Basta visualizar o index de Material Estudo, editar e notificar. Testar o botão de excluir também!
sem prints
**Certifique-se de revisar o código e testar as alterações …
> Feito as alterações solicitadas na reunião.

- Codigo/GestaoGrupoMusicalWeb/Controllers/InformativoController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Informativo/Index.cshtml
</div>
- Arrumar erro de compilação na controller
- Adicionar rota corretamente na view de index
Não tem
Basta ir para view de index, criar e editar.
sem print
> Fix - Controller e rotas na view index de Informativo

- Codigo/Core/Service/IInformativoService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/InformativoController.cs
- Codigo/GestaoGrupoMusicalWeb/Models/InformativoViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Informativo/Create.cshtml
- Codigo/Service/InformativoService.cs
</div>
Alterar campos da página "Create": o campo Data traz a data atual e, após a criação do informativo, o usuário é notificado via e-mail.
Vá na opção do Layout Informativo, clique em "Novo Informativo", adicione um texto no campo Mensagem e escolha entre "Sim" e "Não" no campo Associado Ativo. Clique no botão "Adicionar". Depois, verifique seu e-mail e veja se a mensagem chegou.
> Alteracao na Create de Informativo

- Codigo/Core/Core.csproj
- Codigo/Core/DTO/EventoDTO.cs
- Codigo/Core/DTO/EventoIndexDTO.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Evento/Index.cshtml
- Codigo/Service/EventoService.cs
</div>
Implementar a view de index de eventos
Modifiquei a class de eventoIndexDTO de acordo com oque se pede na tela. Também apaguei a classe de EventoIndexDTO que tinha e coloquei ela dentro de EventoDTO, para que tudo que esteja relacionado ao evento fique mais fácil de operar.
Basta ir para tela principal de eventos (index)
Sem prints
> Implementar view de index de eventos de acordo com o prototipo.

- Codigo/Core/Service/IEnsaioService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
- Codigo/GestaoGrupoMusicalWeb/Models/EnsaioViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Create.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Index.cshtml
- Codigo/Service/EnsaioService.cs
</div>
Consertar algum detalhes que faltaram no caso de uso Manter Ensaio.
Entre na página de Ensaios, clique no botão "Novo Ensaio", preencha os campos. Após isso, o sistema te levará à página de Ensaios. Teste a remoção de um ensaio clicando no botão "Excluir" e, com outro novo ensaio, teste a notificação via e-mail.
> Fix de manter ensaios

- Codigo/GestaoGrupoMusicalWeb/Controllers/InformativoController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Informativo/Index.cshtml
> Operação implementada. Resolve #570

- Codigo/Core/DTO/EventoDTO.cs
- Codigo/Core/Service/IEventoService.cs
- Codigo/Service/EventoService.cs
</div>
Implementar o Gerenciamento de Instrumento para Evento
Implementação da Classe GerenciamentoInstrumentoEventoDTO.
Clicar em gerenciarmento de solução com o botão direito do mouse, em seguida clicar em **Compilar Solução.**
> Implementação do GerenciarInstrumentoEventoDTO.

- Codigo/Core/DTO/EventoDTO.cs
- Codigo/Core/DTO/FigurinoDTO.cs
- Codigo/Core/DTO/PessoaEnviarEmailDTO.cs
- Codigo/Core/Service/IFigurinoService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
- Codigo/GestaoGrupoMusicalWeb/Mapper/EventoProfile.cs
- Codigo/GestaoGrupoMusicalWeb/Models/EventoViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Evento/Create.cshtml
- Codigo/Service/FigurinoService.cs
</div>
- View de Create
- Evento Controller
- Evento Service
- []
Acho que não teve ~acho
Ainda não está funcionando 100%, mas já da para ter uma ideia da view rsrs
> Vere implementar view create eventos 588

- Codigo/Service/EventoService.cs
- Codigo/Service/InstrumentoMusicalService.cs
</div>
Implementar a tela para gerenciar instrumentos musicais em eventos.
Compliar aplicação
> 599 - Implementar Gerenciamento de Instrumento Evento

- Codigo/Core/DTO/EventoDTO.cs
- Codigo/Core/Service/IEventoService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
- Codigo/GestaoGrupoMusicalWeb/Mapper/EventoProfile.cs
- Codigo/GestaoGrupoMusicalWeb/Models/EventoViewModel.cs
- Codigo/Service/EventoService.cs
</div>
Implementaçãod e Create
Nenhuma.
Apenas rodar o programa e fingir que está adicionando, pois ainda falta finalizar a última parte da service para adicionar todas as solicitações vinda para o banco.
Sem prints.
> Implementacao da view create de Eventos - Nao finalizada por completo

- Codigo/Core/Service/IEventoService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
- Codigo/Service/EventoService.cs
</div>
- Imeplentar a service de criar evento
- Deletei o model que estava sendo passado na função index da controller de Eventos, pois não estava tendo utilizade.
OBS: Na tabela de Instrumento, adicione um instrumento com ID = 0 com qualquer nome como "Nenhum" através de linha de código SQL que foi oque dosea recomendou na hora de criar regentes associado ao EventoPessoa para evitar criar outra tabela só para isso.
Depois de ter feito isso, só ir na view e adicionar normalmente.
Essa alteração implicou na funcionalidade "Delete", pois "Delete" não pode deletar um evento sendo que pode linhas das tabelas ApresentacaoFigurino e EventoPessoa associado por chave estrangeira. Dito isso, vou mexer na funcionalidade de Delete para precaver esse …
> Implementado a funcionalidade do Service.

- Codigo/Core/DTO/EventoFrequenciaDTO.cs
> Não implementado por completo, Frequência Evento

- Codigo/Core/DTO/EventoDTO.cs
- Codigo/Core/Service/IEventoService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
- Codigo/GestaoGrupoMusicalWeb/GestaoGrupoMusicalWeb.csproj
- Codigo/GestaoGrupoMusicalWeb/Models/EventoViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Evento/GerenciarInstrumentoEvento.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Evento/Index.cshtml
- Codigo/Service/EventoService.cs
</div>
Implementar View Gerenciamento Instrumento em Evento Musical
Acessar o menu da lateral esquerda, encontrar a opção **Evento**, em seguida clicar no botão **Instrumentos**
> 599   implementar gerenciamento instrumento evento

- Codigo/Core/Service/IEnsaioService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
- Codigo/GestaoGrupoMusicalWeb/Mapper/EnsaioProfileDTO.cs
- Codigo/GestaoGrupoMusicalWeb/Models/EnsaioViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/RegistrarFrequencia.cshtml
- Codigo/Service/EnsaioService.cs
</div>
Implementar registro de frequencia de ensaio.
Com um ensaio adicionado, aperte no botao Frequencia, nao esta funcionando por causa que os dados do ensaio estao vindo nulos.
> Implementar Registro de Frequencia de Ensaio

- Codigo/Core/Service/IEventoService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Evento/Create.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Evento/Edit.cshtml
- Codigo/Service/EventoService.cs
</div>
Implementar a a funcionalidade de edit evento
Eu modifiquei na view de Create de Eventos uma coisa lá que estava com o nome de "Ensaio" para "Evento" do aspnet.
Basta clicar no botão de Edit, porém, a funcionalidade da service ainda não foi finalizada. Mas os dados estão chegando na view de Edit normalmente.
Sem prints
> Implementar a funcionalidade de edit evento

- Codigo/Core/Service/IEventoService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
- Codigo/Service/EventoService.cs
</div>
Implementar a funcionalidade de Editar um evento
Não houve.
Basta ir em Eventos e editar um. Também verificar se as datas batem de acordo com os erros.
Sem prints
> Implementado a funcionalidade do service de Edit Evento

- Codigo/Core/DTO/GerenciarInstrumentoEventoDTO.cs
- Codigo/Core/Service/IEventoService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
- Codigo/GestaoGrupoMusicalWeb/Models/EventoViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Evento/GerenciarInstrumentoEvento.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Evento/_TabelaGerenciarInstrumento.cshtml
- Codigo/Service/EventoService.cs
</div>
Implementação parcial da funcionalidade instrumentos planejados.
Complilar aplicação, acessar o **menu evento > instrumentos.**
> 614 implementar tabela instrumento planejado evento

- Codigo/Core/Service/IEnsaioService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
- Codigo/Service/EnsaioService.cs
</div>
Como ensaio possui relacao com multiplas tabelas, foi necessario atualizar a funcao delete.
Clique no botao Excluir, na tela de Ensaios.
> Implementar delete de Ensaios

- Codigo/Core/DTO/EventoFrequenciaDTO.cs
- Codigo/Core/Service/IEventoService.cs
</div>
Alteração da DTO e IEventoService
> 634 implementar registro frequencia evento

- Codigo/Core/DTO/AssociadoDTO.cs
- Codigo/Core/Service/IPessoaService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
- Codigo/GestaoGrupoMusicalWeb/Models/EnsaioViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/RegistrarFrequencia.cshtml
- Codigo/Service/PessoaService.cs
Tentativa de pegar os dados dos associados ativos, nao deu certo
</div>
Implementar Registro de Frequencia
Abra o menu Ensaios, clique em Frequencia, porem nao ira funcionar, pois os dados de associados ativos esta nulo.
> Implementar Registro de Frequencia

- Codigo/Core/Service/IEventoService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
</div>
Fix - Erro de compilação
Não houve.
Basta rodar o programa normalmente e não vai ter erros no VS Code.
> Fix - removido erro de compilacao

- AnaliseProjeto/Dump de dados.txt
- Codigo/Core/DTO/EventoFrequenciaDTO.cs
LOGIN: 12345678901
SENHA: adm@123
> Implementação de dump de dados

- Codigo/Core/Service/IInformativoService.cs
- Codigo/Core/Service/IMaterialEstudoService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/InformativoController.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/MaterialEstudoController.cs
- Codigo/Service/InformativoService.cs
- Codigo/Service/MaterialEstudoService.cs
</div>
Implementação da index de informativo com o Getdatapage
- Service e a rota na controller foi modificada para tentar pegar os dados.
Não houve.
Ainda não da para testar porque estou com algum problema na hora de pegar os dados.
Sem prints
> Implementando a index de Informativo

- Codigo/Core/DTO/AssociadoDTO.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/RegistrarFrequencia.cshtml
</div>
Implementar Registro de Frequencia em Ensaio
Antes de rodar o codigo, va na funcao, RegistrarFrequencia, modifique a linha que contem idEnsaio, e selecione um que vc tenha criado 
> Implementar REgistro de Frequencia em Ensaio

- Codigo/Core/DTO/InformativoDTO.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/InformativoController.cs
- Codigo/GestaoGrupoMusicalWeb/Mapper/InformativoProfile.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Informativo/Index.cshtml
- Codigo/Service/InformativoService.cs
</div>
Terminar a view de index de Informativo
Não houve.
Basta ir para index de informativo e usar o "Search/Pesquisa" para procurar um informativo. OBS: Caso o nome do seu informativo seja "NOVA Informacao", pode pesquisar sem se preocupar com letras maiúsculas e mínusculas. Da para pesquisar pela data também!
Sem prints
> Finalizado implementacao da index de informativo

- Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
</div>
Fazer com que o código fosse compilado sem erros
Rodar a aplicação
> Fix compilacao

- Codigo/Core/Service/IPessoaService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
- Codigo/GestaoGrupoMusicalWeb/Models/EnsaioViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/RegistrarFrequencia.cshtml
- Codigo/Service/PessoaService.cs
</div>
Implementar registro de frequencia de ensaio
Ter um ensaio cadastrado e clicar no botao Frequencia
> Agora os dados dos associados ativos aparecem!

- Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
</div>
Consertar a rota de RegistrarFrequencia, passando o id selecionado do ensaio
Clique no botao Frequencia de um ensaio
> Fix rota de RegistrarFrequencia

- Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/RegistrarFrequencia.cshtml
</div>
Implementar design system na tabela de associados e colocar os campos de ensaio como readonly
Clique no botão Frequência de Ensaio.
> Colocando design system na tabela de associados

- Codigo/GestaoGrupoMusical.sln
> Adicionado o sln

- AnaliseProjeto/v_dump_grupo_musical_referente_MD.sql
- Codigo/Core/DTO/EventoDTO.cs
- Codigo/Core/Service/IEventoService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
- Codigo/GestaoGrupoMusicalWeb/Models/EventoViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Evento/GerenciarSolicitacaoEvento.cshtml
- Codigo/GestaoGrupoMusicalWeb/appsettings.json
- Codigo/Service/EventoService.cs
</div>
Implementacao de Solicitacao de associados na  Service de Evento.
Eu atualizeo o Dump. Voce pode executar o dump, va para a pasta  "AnaliseProjeto" e tem dois arquivo "v_...", um termina com "MD" que são as contas que você pode autenticar. Autentique como Colaborador, depois va para a tela de Eventos -> Solicitacao. Em seguida, altere o INSCRITO para INDEFERIDO ou DEFERIDO e vice-versa. Você pode ir no banco na consulta e fazer uma consulta para ver as coisas sendo alteradas do associado, como o STATUS passando de X para Y.  O associado tem o ID5 Kah Ales e na apresentacaoTipoInstrumento, quando o associado sai de INSCRITO ou INDEFERIDO para DEFERIDO, incrementa +1 no campo "QuantidadeConfirmada" da tabela "ApresentacaoTipoInstrumento", e …
> Branch finalizar solicitacao grupo musical 664

- Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/RegistrarFrequencia.cshtml
</div>
Aperte no botão Frequência, na tela de Ensaio.
> Update em Registro de Frequência em Ensaio

- Codigo/GestaoGrupoMusicalWeb/Views/Evento/Index.cshtml
- Codigo/Service/EventoService.cs
</div>
Pegar os dados de planejado e confirmado de um evento
Não houve.
Você pode ir no banco e inserir manualmente linhas na tabela de "Apresentacaotipoinstrumento". Vou deixar uma print.
Essa funcionalidade é de Evento -> Index.
> Fix - finalizado index de evento

- Codigo/Core/DTO/AssociadoDTO.cs
- Codigo/Core/Service/IEnsaioService.cs
- Codigo/Core/Service/IFigurinoService.cs
- Codigo/Core/Service/IPessoaService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
- Codigo/GestaoGrupoMusicalWeb/Mapper/EnsaioProfile.cs
- Codigo/GestaoGrupoMusicalWeb/Models/EnsaioViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/RegistrarFrequencia.cshtml
- Codigo/Service/EnsaioService.cs
- Codigo/Service/FigurinoService.cs
- Codigo/Service/PessoaService.cs
</div>
Finalizar registrar frequência de ensaio
Apenas abra uma frequência de Ensaio
> Dados de ensaio, devidamente corretos em RegistrarFrequencia de Ensaio

- Codigo/Core/DTO/AssociadoEventoDTO.cs
- Codigo/Core/Service/IEventoService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
- Codigo/GestaoGrupoMusicalWeb/Models/EventoJustificativaViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Models/EventoViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Evento/Index.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Evento/RegistrarFrequencia.cshtml
- Codigo/Service/EventoService.cs
</div>
Implementar registro frequência de evento
Basta clicar em frequência na tela de evento
> Implementada as funcionalidades

- Codigo/Core/DTO/AssociadoDTO.cs
- Codigo/Core/DTO/EnsaioFrequenciaDTO.cs
- Codigo/Core/Service/IEnsaioService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
- Codigo/GestaoGrupoMusicalWeb/Mapper/EnsaioProfile.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/RegistrarFrequencia.cshtml
- Codigo/Service/EnsaioService.cs
</div>
Abra a tela de frequência do ensaio, marque os checkbox que achar necessário, e clique em salvar, nada será salvo no banco, mas os dados serão mostrados no terminal do projeto.
> Registro de Frequência de Ensaio quase concluído

- Codigo/GestaoGrupoMusicalWeb/Views/Evento/RegistrarFrequencia.cshtml
</div>
Implementar Registro Frequência
Entrar como administrador, já ter um regente cadastrado -> View eventos -> frequência
Verificar se aparece os Regestes e os Figurinos.
OBS: Não está funcionando por completo, caso aperte no botão Salvar e não funcionar, falta ajustes tanto visuais também.
> Implementada visualização regentes e figurinos na view RegistrarFrequencia.cshtml

- Codigo/Core/DTO/EnsaioFrequenciaDTO.cs
- Codigo/Core/Service/IEnsaioService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
- Codigo/Service/EnsaioService.cs
</div>
Sem êxito na hora de salvar no banco
> Registro Frequência de Ensaio

- Codigo/Core/DTO/FinanceiroDTO.cs
- Codigo/Core/Service/IFinanceiroService.cs
- Codigo/Core/Service/IPessoaService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/FinanceiroController.cs
- Codigo/GestaoGrupoMusicalWeb/Mapper/FinanceiroProfile.cs
- Codigo/GestaoGrupoMusicalWeb/Models/FinanceiroCreateViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Models/FinanceiroViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Evento/GerenciarSolicitacaoEvento.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Financeiro/Create.cshtml
- Codigo/Service/FinanceiroService.cs
- Codigo/Service/PessoaService.cs
</div>
Imeplementar funcionalidade de novo pagamento.
Não houve
Basta ir para a tela de financeiro e adicionar um novo pagamento. Pode verificar no banco que quando uma linha na tabela de pagamento é adicionado, é adicionado várias linhas na tabela de FinanceiroPessoa para associados pagar.
> 687 implementar novo pagamento

- Codigo/GestaoGrupoMusicalWeb/Models/EventoViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Evento/RegistrarFrequencia.cshtml
</div>
Implementar Registro Frequência
Na view Eventos -> Frequência, analisar se está de acordo a visualização da view conforme específicado
> 695 implementar visualizao registro frequncia

- Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/RegistrarFrequencia.cshtml
- Codigo/Service/EnsaioService.cs
</div>
Aqui só consegui testar apenas uma vez, e realmente funcionou, acredito que tenha que criar mais ensaios para poder testar mais desta funcionalidade, pena que o criar ensaio não esteja funcionando para isto.
> Registrar Frequência de Ensaio implementada

- Codigo/Core/DTO/GerenciarInstrumentoEventoDTO.cs
- Codigo/Core/DTO/InstrumentoPlanejadoEventoDTO.cs
- Codigo/Core/Service/IEventoService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
- Codigo/GestaoGrupoMusicalWeb/Models/EventoViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Evento/_TabelaGerenciarInstrumento.cshtml
- Codigo/Service/EventoService.cs
</div>
Exibir tabela com instrumentos planejados em um determinado evento
Acessando a view instrumento eventos, serviceEvento, ControllerEvento.
> 689 implementar visualização de instrumentos planejados evento

- AnaliseProjeto/v_dump_grupo_musical_referente_MD.md
- AnaliseProjeto/v_dump_grupo_musical_referente_MD.sql
- Codigo/Core/Service/IEnsaioService.cs
- Codigo/Core/Service/IPessoaService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
- Codigo/GestaoGrupoMusicalWeb/Models/EnsaioViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Edit.cshtml
- Codigo/Service/EnsaioService.cs
- Codigo/Service/PessoaService.cs
</div>
Ao inserir 1 linha em ensaio, agora já insere N associados ATIVOS.
Removi assincrono de alguns metodos.
Tambem adicionei um novo dump com mais pessoas adicionada. Basta atualizar o dump no seu banco.
Basta criar um novo Ensaio e ver no banco sendo criado N linhas para ensaio.
> 700 fix   ao adicionar tabelas ja inserir associados dentro

- Codigo/Core/DTO/AssociadoDTO.cs
- Codigo/Core/Service/IEnsaioService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/RegistrarFrequencia.cshtml
- Codigo/Service/EnsaioService.cs
</div>
Corrigir erro de deletar a descricao do associado quando alterava a frequencia. Também houve um bug alterando o papelGrupo do associado.
Nao houve.
Basta ir para Ensaio -> Frequencia -> Mexer nas checkBox dos associados -> Registrar
Sem prints
> fix  edicao de frequncia deletando dados de descricao do associado e alterando o papel grupo

- Codigo/GestaoGrupoMusicalWeb/Controllers/MaterialEstudoController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/_ViewStart.cshtml
> Corrigido problema de barra lateral do associado. #Resolved 718

- Codigo/GestaoGrupoMusicalWeb/Views/Identity/Perfil.cshtml
> Tela de visualização feita, com botão voltar adicionado. Resolved #724

- Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Edit.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Evento/Edit.cshtml
> Corrigido os campos de regente em editar de Ensaios e Eventos

- Codigo/GestaoGrupoMusicalWeb/Controllers/IdentityController.cs
- Codigo/GestaoGrupoMusicalWeb/Models/UserViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Identity/Perfil.cshtml
> Corrigido os dados faltantes nos perfis de regente e administrador #736

- Codigo/GestaoGrupoMusicalWeb/Controllers/BaseController.cs
> Corrigido o problema de redefinição de senha #735

- Codigo/GestaoGrupoMusicalWeb/appsettings.json
</div>
Adicionar o arquivo de configuração do projeto contendo a string de conexão do banco de dados do servidor.
Basta executar o projeto
> Adicionado o arquivo de configuração.

- Codigo/Core/Service/IInformativoService.cs
- Codigo/ServiceTests/InformativoServiceTests.cs
Corrigido pendências nos testes.
> Corrigido pendências nos testes.

- Codigo/GestaoGrupoMusicalWeb/Controllers/InformativoController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Informativo/Index.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutAssociado.cshtml
> Funcionalidade de informativos para associado implementada.

- Codigo/Core/Service/IFinanceiroService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/FinanceiroController.cs
- Codigo/GestaoGrupoMusicalWeb/Mapper/FinanceiroProfile.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Financeiro/Delete.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Financeiro/Delete.cshtml.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Financeiro/Details.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Financeiro/Details.cshtml.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Financeiro/Edit.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Financeiro/Index.cshtml
- Codigo/Service/FinanceiroService.cs
Implementa as funcionalidades de Editar, Excluir e Detalhes no módulo Financeiro, completando o CRUD. As novas telas foram padronizadas para seguir o estilo visual do sistema e a tabela da página Index foi corrigida.
> Feito as views Details, Edit e Delete do Financeiro.

- Codigo/Core/Service/IEnsaioService.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/FinanceiroController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Details.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Index.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Financeiro/Index.cshtml
- Codigo/Service/EnsaioService.cs
- Codigo/Service/FinanceiroService.cs
Adicionada a funcionalidade de "Detalhes" ao módulo de Ensaio, incluindo a criação da view e action. Corrigido a consulta de regentes para exibir apenas os alocados ao ensaio específico e ajusta o layout da tela de detalhes para melhor organização visual.
> Criado a visualização do ensaio.

- Codigo/Core/Eventopessoa.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
- Codigo/GestaoGrupoMusicalWeb/Models/EventoViewModel.cs
- Codigo/Service/EventoService.cs
> Problema com criação e edição de Evento corrigido #755

- Codigo/GestaoGrupoMusicalWeb/Views/_ViewStart.cshtml
> Fix visualização do adm do sistema

- Codigo/Core/Apresentacaotipoinstrumento.cs
- Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
- Codigo/GestaoGrupoMusicalWeb/Models/EventoViewModel.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Evento/GerenciarInstrumentoEvento.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Evento/_GerenciarInstrumentoEvento.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Evento/_TabelaGerenciarInstrumento.cshtml
- Codigo/Service/EventoService.cs
> Fix: Visualização de instrumentos no evento.

- Codigo/GestaoGrupoMusicalWebTests/Controllers/FigurinoControllerTests.cs
> Fix: logger de figurino.

- Codigo/GestaoGrupoMusicalWeb/Controllers/FinanceiroController.cs
- Codigo/Service/FinanceiroService.cs
Correções e Melhorias no Módulo Financeiro
- Ajusta os cálculos de Atrasos, Isentos e Recebido para refletirem corretamente os status e valores dos pagamentos.
- Permite o salvamento parcial de pagamentos e automatiza o registro de isenção para melhorar a usabilidade.
> Ajusta lógicas de cálculo de pagamentos, atrasos, isentos e recebidos

- Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
- Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/EnsaiosAssociado.cshtml
- Codigo/GestaoGrupoMusicalWeb/Views/Evento/SolicitarParticipacao.cshtml
- Codigo/Service/EventoService.cs
</div>
Solicitação para participar do evento não estava funcionando.
> Chore: solicitacao para evento totalmente funcional.

- Codigo/GestaoGrupoMusicalWeb/Views/Financeiro/Pag_Associados.cshtml
</div>
Correção dos campos de status em pagamento.
> Fix: status dos pagamentos com valores corretos.
